# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Brand.destroy_all

Brand.create!([
{
	name: "Arsenal",
	website: "http://www.arsenal.com",
	facebook_url: "https://www.facebook.com/Arsenal",
	fb_joined: "27/12/2007",
	twitter_url: "Arsenal",
	twitter_joined: "23/04/2009",
	youtube_url: "https://www.youtube.com/user/ArsenalTour",
	yt_joined: "04/06/2013",
	pinterest_url: "",
	instagram_url: "https://instagram.com/arsenal/",
	linkedin_url: "",
	google_plus: "",
	wikipedia_url: "en.wikipedia.org/wiki/Arsenal_F.C.",
	stadium: "Emirates Stadium",
	stadium_capacity: 60361,
	user_id: 1,
	category_id: 1,
	hex: "ef0107",
	sport: "Football",
	league: "Premiership",
	country: "ENG",
	logo_file_name: "images/Football/Premiership/arsenal40x40.png"
},
{
	name: "Aston Villa",
	website: "www.avfc.co.uk",
	facebook_url: "https://www.facebook.com/avfcofficial",
	fb_joined: "26/04/2010",
	twitter_url: "AVFCOfficial",
	twitter_joined: "29/03/2009",
	youtube_url: "http://www.youtube.com/user/avfcofficial",
	yt_joined: "20/04/2011",
	pinterest_url: "",
	instagram_url: "https://instagram.com/avfcofficial",
	linkedin_url: "",
	google_plus: "https://plus.google.com/+avfcofficial/about",
	wikipedia_url: "en.wikipedia.org/wiki/Aston_Villa_F.C.",
	stadium: "Villa Park",
	stadium_capacity: 42788,
	user_id: 1,
	category_id: 1,
	hex: "7a003c",
	sport: "Football",
	league: "Premiership",
	country: "ENG"
},
{
	name: "Chelsea",
	website: "www.chelseafc.com",
	facebook_url: "www.facebook.com/chelseafc",
	fb_joined: "28/07/2009",
	twitter_url: "chelseafc",
	twitter_joined: "05/03/2009",
	youtube_url: "https://www.youtube.com/user/chelseafc",
	yt_joined: "28/02/2006",
	pinterest_url: "",
	instagram_url: "https://instagram.com/chelseafc/",
	linkedin_url: "",
	google_plus: "https://plus.google.com/+chelseafc/posts",
	wikipedia_url: "en.wikipedia.org/wiki/Chelsea_F.C.",
	stadium: "Stamford Bridge",
	stadium_capacity: 41837,
	user_id: 1,
	category_id: 1,
	hex: "034694",
	sport: "Football",
	league: "Premiership",
	country: "ENG"
},
{
	name: "Crystal Palace",
	website: "http://www.cpfc.co.uk/",
	facebook_url: "https://www.facebook.com/officialcpfc",
	fb_joined: "",
	twitter_url: "cpfc",
	twitter_joined: "26/10/2009",
	youtube_url: "https://www.youtube.com/user/OfficialCPFC",
	yt_joined: "02/08/2011",
	pinterest_url: "",
	instagram_url: "https://instagram.com/official_cpfc/",
	linkedin_url: "",
	google_plus: "",
	wikipedia_url: "en.wikipedia.org/wiki/Crystal_Palace_F.C.",
	stadium: "Selhurst Park",
	stadium_capacity: 26309,
	user_id: 1,
	category_id: 1,
	hex: "c41230",
	sport: "Football",
	league: "Premiership",
	country: "ENG"
},
{
	name: "Everton",
	website: "www.evertonfc.com",
	facebook_url: "https://www.facebook.com/Everton",
	fb_joined: "12/02/2009",
	twitter_url: "Everton",
	twitter_joined: "18/08/2008",
	youtube_url: "https://www.youtube.com/user/OfficialEverton",
	yt_joined: "23/09/2011",
	pinterest_url: "",
	instagram_url: "https://instagram.com/everton/",
	linkedin_url: "",
	google_plus: "",
	wikipedia_url: "en.wikipedia.org/wiki/Everton_F.C.",
	stadium: "Goodison Park",
	stadium_capacity: 40157,
	user_id: 1,
	category_id: 1,
	hex: "01aae5",
	sport: "Football",
	league: "Premiership",
	country: "ENG"
},
{
	name: "Manchester City",
	website: "www.mcfc.co.uk",
	facebook_url: "http://www.facebook.com/mcfcofficial",
	fb_joined: "07/07/2009",
	twitter_url: "mcfc",
	twitter_joined: "23/04/2008",
	youtube_url: "https://www.youtube.com/user/mcfcofficial",
	yt_joined: "07/07/2009",
	pinterest_url: "",
	instagram_url: "https://instagram.com/mcfcofficial/",
	linkedin_url: "",
	google_plus: "https://plus.google.com/+mcfcofficial/posts",
	wikipedia_url: "en.wikipedia.org/wiki/Manchester_City_F.C.",
	stadium: "City of Manchester Stadium",
	stadium_capacity: 47726,
	user_id: 1,
	category_id: 1,
	hex: "5cbfef",
	sport: "Football",
	league: "Premiership",
	country: "ENG"
},
{
	name: "Manchester United",
	website: "www.manutd.com",
	facebook_url: "www.facebook.com/manchesterunited",
	fb_joined: "29/08/2009",
	twitter_url: "ManUtd",
	twitter_joined: "22/06/2011",
	youtube_url: "",
	yt_joined: "",
	pinterest_url: "",
	instagram_url: "https://instagram.com/manchesterunited/",
	linkedin_url: "",
	google_plus: "https://plus.google.com/107337299762605675178",
	wikipedia_url: "en.wikipedia.org/wiki/Manchester_United_F.C.",
	stadium: "Old Trafford",
	stadium_capacity: 75765,
	user_id: 1,
	category_id: 1,
	hex: "d0020d",
	sport: "Football",
	league: "Premiership",
	country: "ENG"
},
{
	name: "Newcastle United",
	website: "http://www.nufc.co.uk/",
	facebook_url: "https://www.facebook.com/newcastleunited",
	fb_joined: "05/05/2010",
	twitter_url: "NUFCOfficial",
	twitter_joined: "27/04/2009",
	youtube_url: "https://www.youtube.com/user/NUFCOfficial1892",
	yt_joined: "23/06/2011",
	pinterest_url: "",
	instagram_url: "https://instagram.com/newcastleofficial/",
	linkedin_url: "",
	google_plus: "https://plus.google.com/u/1/b/100267867473028468119/+NewcastleUnited/posts",
	wikipedia_url: "en.wikipedia.org/wiki/Newcastle_United_F.C.",
	stadium: "St James' Park",
	stadium_capacity: 52404,
	user_id: 1,
	category_id: 1,
	hex: "000000",
	sport: "Football",
	league: "Premiership",
	country: "ENG"
},
{
	name: "Sunderland",
	website: "www.safc.com",
	facebook_url: "https://www.facebook.com/sunderlandafc",
	fb_joined: "14/04/2010",
	twitter_url: "sunderlandafc",
	twitter_joined: "31/03/2009",
	youtube_url: "https://www.youtube.com/user/sunderlandafc",
	yt_joined: "06/08/2014",
	pinterest_url: "",
	instagram_url: "https://instagram.com/sunderlandafcofficial/",
	linkedin_url: "",
	google_plus: "https://plus.google.com/+SunderlandAFC/posts",
	wikipedia_url: "en.wikipedia.org/wiki/Sunderland_A.F.C.",
	stadium: "Stadium of Light",
	stadium_capacity: 48300,
	user_id: 1,
	category_id: 1,
	hex: "eb172b",
	sport: "Football",
	league: "Premiership",
	country: "ENG"
},
{
	name: "Tottenham Hotspur",
	website: "www.tottenhamhotspur.com",
	facebook_url: "https://www.facebook.com/TottenhamHotspur",
	fb_joined: "03/03/2010",
	twitter_url: "SpursOfficial",
	twitter_joined: "09/03/2010",
	youtube_url: "http://www.youtube.com/user/spursofficial",
	yt_joined: "30/09/2011",
	pinterest_url: "",
	instagram_url: "https://instagram.com/spursofficial",
	linkedin_url: "",
	google_plus: "https://plus.google.com/109368880984358777249",
	wikipedia_url: "en.wikipedia.org/wiki/Tottenham_Hotspur_F.C.",
	stadium: "White Hart Lane",
	stadium_capacity: 36310,
	user_id: 1,
	category_id: 1,
	hex: "000000",
	sport: "Football",
	league: "Premiership",
	country: "ENG"
},
{
	name: "West Ham",
	website: "www.whufc.com",
	facebook_url: "https://www.facebook.com/westhamunitedofficial",
	fb_joined: "25/06/2010",
	twitter_url: "whufc_official",
	twitter_joined: "16/06/2010",
	youtube_url: "https://www.youtube.com/channel/UCCNOsmurvpEit9paBOzWtUg",
	yt_joined: "01/08/2012",
	pinterest_url: "",
	instagram_url: "https://instagram.com/whufc_official/",
	linkedin_url: "",
	google_plus: "https://plus.google.com/113782126274956055230",
	wikipedia_url: "en.wikipedia.org/wiki/West_Ham_United_F.C.",
	stadium: "The Boleyn Ground",
	stadium_capacity: 35016,
	user_id: 1,
	category_id: 1,
	hex: "60223b",
	sport: "Football",
	league: "Premiership",
	country: "ENG"
},
{
	name: "West Ham",
	website: "www.whufc.com",
	facebook_url: "https://www.facebook.com/westhamunitedofficial",
	fb_joined: "25/06/2010",
	twitter_url: "whufc_official",
	twitter_joined: "16/06/2010",
	youtube_url: "https://www.youtube.com/channel/UCCNOsmurvpEit9paBOzWtUg",
	yt_joined: "01/08/2012",
	pinterest_url: "",
	instagram_url: "https://instagram.com/whufc_official/",
	linkedin_url: "",
	google_plus: "https://plus.google.com/113782126274956055230",
	wikipedia_url: "en.wikipedia.org/wiki/West_Ham_United_F.C.",
	stadium: "The Boleyn Ground",
	stadium_capacity: 35016,
	user_id: 1,
	category_id: 1,
	hex: "60223b",
	sport: "Football",
	league: "Premiership",
	country: "ENG"
}

])

Question.update_all(is_approved: true)

p "-----------------------------------"
p "Created #{Question.count} questions"
p "-----------------------------------"
p "Created #{Brand.count} brands"
p "-----------------------------------"
